### ISSUE TITLE
Unused texture reference?

### ISSUE THREAD

**Issue by yosmo78** [PacktPublishing/Learn-CUDA-Programming#11]
So just like most people here, I am new to CUDA, and because of that I may be totally wrong. However the texture reference declared here: 

https://github.com/PacktPublishing/Learn-CUDA-Programming/blob/bad5c70c4cc1e54dbbdeb10efd5199c8a8ec8483/Chapter02/02_memory_overview/05_image_scaling/image_scaling.cu#L5

doesn't seem to be used, instead we use the texture obj we create in main for texture fetching. So I was wondering if this line is even necessary. I tried commenting it out and running it, and it seemed to compile and run just fine, with the expected results. Then I did a tiny amount of research and it looks like we would use it only if we were binding to some device memory, which again we are not. So this does seem to me to be unused and not needed.

Again I may be wrong, correct me if I am.

Thanks for your time!

**Comment by haanjack** [comment]
Thanks for pointing the unused code.
This part will be removed from the code and the book.

In this code, it creates another texture object `texObj` and used it as a texture memory.
Officially, the CUDA programming guide provides two methods: creation of the global texture object and local texture object. Our version chose the second.
