### ISSUE TITLE
wrong final reduction in all grid-stride loop examples

### ISSUE THREAD

**Issue by mateuszzz88** [PacktPublishing/Learn-CUDA-Programming#15]
All examples in chapter 3 for reduction with grid-stride loop have following calls:
```
    reduction_kernel<<<n_blocks, n_threads>>>(g_outPtr, g_inPtr, size);
    reduction_kernel<<< 1, n_threads, n_threads * sizeof(float), 0 >>>(g_outPtr, g_inPtr, n_blocks);
```
I believe second one should have arguments `(g_outPtr, g_outPtr, n_blocks)` (g_outPtr twice). I think author of this blog post https://developer.nvidia.com/blog/faster-parallel-reductions-kepler/ agrees (note double "out" in `(out, out, blocks)`):
```
  deviceReduceKernel<<<blocks, threads>>>(in, out, N);
  deviceReduceKernel<<<1, 1024>>>(out, out, blocks);
```

**Comment by haanjack** [comment]
Thanks for the pointing.  I agree the second code has issue that you mentioned.
