### ISSUE TITLE
sgemm.cu:6:10: fatal error: helper_functions.h: No such file or directory

### ISSUE THREAD

**Issue by thatrobotguy** [PacktPublishing/Learn-CUDA-Programming#2]
Well, the error pretty well says it all. The code I want to compile is straight up missing the file `helper_functions.h`. Specifically, I am on page 39 of the book looking at the profiling example
```
nvcc -o sgemm sgemm.cu
```
and I can't compile the example code. This is the example under `Chapter02/02_memory_overview/04_sgemm`. I should also mention I `git clone`ed the repository: I am not running the Zip file code (it is really old).

**Comment by haanjack** [comment]
Actually, that header file is a CUDA samples' header file.

You can build the code with the following command.
```
nvcc -o sgemm sgemm.cu -I/usr/local/cuda/samples/common/inc
```
Or, copy a Makefile from ```Chaper03/03_cuda_thread_programming/02_cuda_occupancy```, and ```make```.

**Comment by thatrobotguy** [comment]
The `nvcc` command provided now works as expected.
I also copied the `Makefile` from `02_cuda_occupancy` and it also works.

**Comment by jreuben11** [comment]
nvprof is not supported on devices with compute capability 8.0 and higher
See: Migrating to NVIDIA Nsight Tools from NVVP and Nvprof https://developer.nvidia.com/blog/migrating-nvidia-nsight-tools-nvvp-nvprof/
