### ISSUE TITLE
cannot compile chapter 10 on linux

### ISSUE THREAD

**Issue by thatrobotguy** [PacktPublishing/Learn-CUDA-Programming#3]
`bug`
So I was jumping around the repository to see if I could at least try and run the code and I ran into another issue.
Specifically, I tried compiling the chapter 10 code by `cd`ing to this location:
```
blah/Learn-CUDA-Programming/Chapter10/10_deep_learning/right here
```
and running the `make` command, I get this error:
```
~/nvidiastuff/learncuda/Learn-CUDA-Programming/Chapter10/10_deep_learning$ make
make[1]: Entering directory '/home/thatrobotguy/nvidiastuff/learncuda/Learn-CUDA-Programming/Chapter10/10_deep_learning/01_ann'
/usr/local/cuda/bin/nvcc -ccbin g++ -I/usr/local/cuda/samples/common/inc -I/usr/local/cuda/include -m64 -g -std=c++11 -G --resource-usage -Xcompiler -rdynamic -Xcompiler -fopenmp -rdc=true -lnvToolsExt -I/usr/local/cuda/samples/common/inc -I/usr/local/cuda/include -L/usr/local/cuda/lib -lcublas -lcudnn -lgomp -lcurand -gencode arch=compute_70,code=sm_70 -c train.cpp -o obj/train.o
nvcc warning : Resource usage is not shown as the final resource allocation is not done.
Assembler messages:
Fatal error: can't create obj/train.o: No such file or directory
Makefile:29: recipe for target 'obj/train.o' failed
make[1]: *** [obj/train.o] Error 1
make[1]: Leaving directory '/home/thatrobotguy/nvidiastuff/learncuda/Learn-CUDA-Programming/Chapter10/10_deep_learning/01_ann'
Makefile:7: recipe for target '01_ann/Makefile.ph_build' failed
make: *** [01_ann/Makefile.ph_build] Error 2
```
I know I have GCC set to version 7 since I am running CUDA 10.0 on Ubuntu 18.04, but I don't think my machine is the problem since all of the software paths are known to the `nvcc` compiler (added in my `~/.bashrc` file).

**Comment by haanjack** [comment]
Hi, thanks for informing me.
The reason was no obj directory in the sub-directory so that the object files could not be created. I've updated the Makefile to create the directory.

Please pull the code and see if it works for you.

**Comment by thatrobotguy** [comment]
Yes, the new version of this code compiles now. I appreciate the update.
