### ISSUE TITLE
How to implement a complete LSTM network with cudnn?

### ISSUE THREAD

**Issue by cqiaoYc** [PacktPublishing/Learn-CUDA-Programming#6]
This is a very good book!
I am building a semi supervised learning system with GA + LSTM. I need to build a multi-layer LSTM network with cudnn, which contains several LSTM layers and a softmax output layer. The LSTM network only needs inference function and no training. In the 10_deep_learning/03_rnn/rnn.cpp, you show how to create LSTM layers, but how to connect a LSTM layer and a softmax layer. There should be a density layer in the middle. The output of LSTM layer is 3D, and the input of density layer is 2D. How to convert?

**Comment by packt-pradeeps** [comment]
This is not the right place for this question as this book is not about this topic
